# render.yaml — corrected for exonyBack (MySQL as a private service)
# - This blueprint creates:
#    1) a Node web service (exony-back)
#    2) a private service running MySQL (exony-mysql) from the render-examples/mysql repo
# Notes:
# - You will be prompted to provide any "sync: false" secrets during the initial Blueprint creation.
# - After the initial creation, set DATABASE_URL in the web service env (see instructions below).

services:
  - type: web
    runtime: node
    name: exony-back
    branch: main
    plan: starter
    buildCommand: npm ci && npm run build
    # Use `npm run start` in production to avoid running migrations/seeds on every deploy.
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      # Prompt Render to ask for the connection string during blueprint creation.
      - key: DATABASE_URL
        sync: false

  # MySQL as a private service (uses Render's example MySQL repo)
  - type: pserv
    runtime: docker
    name: exony-mysql
    repo: https://github.com/render-examples/mysql
    branch: main
    plan: starter
    envVars:
      - key: MYSQL_DATABASE
        value: exony
      - key: MYSQL_USER
        value: exony
      # Ask Render to prompt you for these secrets during initial Blueprint creation:
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_ROOT_PASSWORD
        sync: false
